#+title: Quantum Information Project: Self-testing of quantum systems
#+setupfile: misc/theme-readtheorg.setup
#+latex_header: \input{misc/header.tex}

Second semester research project within Sorbonne Université's IQ Master's
degree.

By Hugo Abreu, Fanny Terrier and Hugo Thomas. Supervised by Ivan Šupić.

You can find an HTML version of this document in [[https://thmhugo.github.io/qi-project/]]

* Subject

The subject can be found in the [[file:references/project-self-test.pdf][project description]].

** Objectives

#+begin_quote
- Find the relation between two self-testing conditions:
  - maximal violation of some Bell inequality
  - reproduction of a full-set of measurement correlations
#+end_quote

This equates to finding *Bell inequalities* which are *maximally violated by
measurement correlations which self-test a corresponding quantum state*.

In particular: *relate Mayers-Yao self-testing condition to some Bell inequality*.

If the first part is successful, try to *generalize the Mayers-Yao self-testing
condition to larger classes of entangled states*.

* Notes

** Self testing

#+begin_quote
Self-testing is a method to infer the underlying physics of a quantum experiment
in a black box scenario. --  Self-testing of quantum systems: a review, p.1
#+end_quote

It has both theoretical implications in quantum information theory (as part of
the general study of quantum correlations) and practical applications in quantum
computing protocols:
- validating quantum systems (device-indepent certification)
- device-independent quantum cryptography
- device-independent randomness generation
- ...

*** Definitions

Some notations:
- $\mathcal{L}(\mathcal{H})$ denotes the set of linear operators acting on an
  Hilbert space $\mathcal{H}$.

The self-testing scenario (when device-independent, commonly called a Bell
test):
- Consider two parties $A$ and $B$.

[[file:notes/notes-th.org][Org]]
[[file:notes/notes-th.html][HTML]]
[[file:notes/notes-th.pdf][PDF]]

*** Device-independent scenario

* References
** [[file:references/self-testing-review.pdf][Self-testing of quantum systems: a review (1)]]
** [[file:references/self-testing-apparatus.pdf][Self testing quantum apparatus (2)]]
** [[file:references/bell-nonlocality][Bell nonlocality (3)]]
